const characters = [
  {
    name: "Monkey D. Luffy",
    image: "images/luffy.jpg",
    affiliation: "Strawhat Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "Human-Human, Model: Nika",
      haki: ["Conquerors", "Armament", "Observation"],
    },
    strength: 9,
    isEmperor: true,
    isWarlord: false,
    isWorstGeneration: true,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Roronoa Zoro",
    image: "images/zoro.jpg",
    affiliation: "Strawhat Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "",
      haki: ["Conquerors", "Armament", "Observation"],
    },
    strength: 8,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: true,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Vinsmoke Sanji",
    image: "images/sanji.jpg",
    affiliation: "Strawhat Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "",
      haki: ["Armament", "Observation"],
    },
    strength: 8,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Nami",
    image: "images/nami.jpg",
    affiliation: "Strawhat Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "",
      haki: [],
    },
    strength: 4,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,

    isKing: false,
  },
  {
    name: "Usopp",
    image: "images/usopp.jpg",
    affiliation: "Strawhat Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "",
      haki: [],
    },
    strength: 4,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Tony Tony Chopper",
    image: "images/chopper.jpg",
    affiliation: "Strawhat Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "Human-Human",
      haki: [],
    },
    strength: 4,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Nico Robin",
    image: "images/robin.jpg",
    affiliation: "Strawhat Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "Flower-Flower",
      haki: [],
    },
    strength: 6,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Franky",
    image: "images/franky.jpg",
    affiliation: "Strawhat Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "",
      haki: [],
    },
    strength: 6,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Brook",
    image: "images/brook.jpg",
    affiliation: "Strawhat Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "Revive-Revive",
      haki: [],
    },
    strength: 6,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Jinbe",
    image: "images/jinbe.jpg",
    affiliation: "Strawhat Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "",
      haki: ["Armament"],
    },
    strength: 7,
    isEmperor: false,
    isWarlord: true,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Figarland Shanks",
    image: "images/shanks.jpg",
    affiliation: "Red Haired Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: null,
      haki: ["Conquerors", "Armament", "Observation"],
    },
    strength: 10,
    isEmperor: true,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Marshall D. Teach",
    image: "images/blackbeard.jpg",
    affiliation: "Black Beard Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "Dark-Dark, Tremor-Tremor",
      haki: ["Conquerors", "Armament", "Observation"],
    },
    strength: 10,
    isEmperor: true,
    isWarlord: false,
    isWorstGeneration: true,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Kaido",
    image: "images/kaido.jpg",
    affiliation: "Beast Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "Fish-Fish, Azure Dragon Model",
      haki: ["Conquerors", "Armament", "Observation"],
    },
    strength: 9,
    isEmperor: true,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Charlotte Linlin",
    image: "images/bigmom.jpg",
    affiliation: "Big Mom Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "Soul-Soul",
      haki: ["Conquerors", "Armament", "Observation"],
    },
    strength: 9,
    isEmperor: true,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Buggy",
    image: "images/buggy.jpg",
    affiliation: "Buggy Pirates/Cross Guild",
    faction: "Pirate",
    abilities: {
      devilFruit: "Chop-Chop",
      haki: ["Conquerors", "Armament", "Observation"],
    },
    strength: 7,
    isEmperor: true,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Sakazuki",
    image: "images/akainu.jpg",
    affiliation: "Admirals",
    faction: "Navy",
    abilities: {
      devilFruit: "Magma-Magma",
      haki: ["Armament", "Observation"],
    },
    strength: 9,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: true,
    isKing: false,
  },
  {
    name: "Kuzan",
    image: "images/aokiji.jpg",
    affiliation: "Admirals",
    faction: "Navy",
    abilities: {
      devilFruit: "Ice-Ice",
      haki: ["Armament", "Observation"],
    },
    strength: 9,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: true,
    isKing: false,
  },
  {
    name: "Borsalino",
    image: "images/kizaru.jpg",
    affiliation: "Admirals",
    faction: "Navy",
    abilities: {
      devilFruit: "Ice-Ice",
      haki: ["Armament", "Observation"],
    },
    strength: 9,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: true,
    isKing: false,
  },
  {
    name: "Rob Lucci",
    image: "images/lucci.jpg",
    affiliation: "CP-0",
    faction: "Government",
    abilities: {
      devilFruit: "Cat-Cat, Model: Leopard",
      haki: ["Armament", "Observation"],
    },
    strength: 9,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Kaku",
    image: "images/kaku.jpg",
    affiliation: "CP-0",
    faction: "Government",
    abilities: {
      devilFruit: "Ox-Ox, Model: Giraffe",
      haki: ["Armament", "Observation"],
    },
    strength: 7,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Monkey D. Garp",
    image: "images/garp.jpg",
    affiliation: "Vice Admiral",
    faction: "Navy",
    abilities: {
      devilFruit: null,
      haki: ["Conquerors", "Armament", "Observation"],
    },
    strength: 8,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Koby",
    image: "images/koby.jpg",
    affiliation: "SWORD",
    faction: "Navy",
    abilities: {
      devilFruit: null,
      haki: ["Armament", "Observation"],
    },
    strength: 7,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Monkey D. Dragon",
    image: "images/dragon.jpg",
    affiliation: "Revolutionary Army",
    faction: "Revolutionary Army",
    abilities: {
      devilFruit: "Unknown",
      haki: [],
    },
    strength: 7,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Sabo",
    image: "images/sabo.jpg",
    affiliation: "Revolutionary Army",
    faction: "Revolutionary Army",
    abilities: {
      devilFruit: "Flame-Flame",
      haki: ["Armament", "Observation"],
    },
    strength: 8,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Koala",
    image: "images/koala.jpg",
    affiliation: "Revolutionary Army",
    faction: "Revolutionary Army",
    abilities: {
      devilFruit: null,
      haki: [],
    },
    strength: 4,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Kozuki Oden",
    image: "images/oden.jpg",
    affiliation: "Roger Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: null,
      haki: ["Conquerors", "Armament", "Observation"],
    },
    strength: 8,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Gol D. Roger",
    image: "images/roger.jpg",
    affiliation: "Roger Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: null,
      haki: ["Conquerors", "Armament", "Observation"],
    },
    strength: 10,
    isEmperor: true,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: true,
  },
  {
    name: "Silvers Rayleigh",
    image: "images/rayleigh.jpg",
    affiliation: "Roger Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: null,
      haki: ["Conquerors", "Armament", "Observation"],
    },
    strength: 8,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Edward Newgate",
    image: "images/whitebeard.jpg",
    affiliation: "Whitebeard Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "Tremor-Tremor",
      haki: ["Conquerors", "Armament", "Observation"],
    },
    strength: 9,
    isEmperor: true,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Marco",
    image: "images/marco.jpg",
    affiliation: "Whitebeard Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "Bird-Bird, Model: Phoenix",
      haki: ["Armament", "Observation"],
    },
    strength: 7,
    isEmperor: true,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Portgas D. Ace",
    image: "images/ace.jpg",
    affiliation: "Whitebeard Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "Flame-Flame",
      haki: ["Conquerors", "Armament", "Observation"],
    },
    strength: 8,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Charlotte Katakuri",
    image: "images/katakuri.jpg",
    affiliation: "Big Mom Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "Mochi-Mochi",
      haki: ["Conquerors", "Armament", "Observation"],
    },
    strength: 8,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Dracule Mihawk",
    image: "images/mihawk.jpg",
    affiliation: "Cross Guild",
    faction: "Pirate",
    abilities: {
      devilFruit: null,
      haki: ["Armament", "Observation"],
    },
    strength: 9,
    isEmperor: false,
    isWarlord: true,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Donquixote Doflamingo",
    image: "images/doffy.jpg",
    affiliation: "Donquixote Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "String-String",
      haki: ["Conquerors", "Armament", "Observation"],
    },
    strength: 8,
    isEmperor: false,
    isWarlord: true,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Gecko Moria",
    image: "images/moria.jpg",
    affiliation: "Thriller Bark Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "Shadow-Shadow",
      haki: [],
    },
    strength: 6,
    isEmperor: false,
    isWarlord: true,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Crocodile",
    image: "images/crocodile.jpg",
    affiliation: "Cross Guild",
    faction: "Pirate",
    abilities: {
      devilFruit: "Sand-Sand",
      haki: [],
    },
    strength: 8,
    isEmperor: false,
    isWarlord: true,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Bartholomew Kuma",
    image: "images/kuma.jpg",
    affiliation: "Revolutionary Army",
    faction: "Revolutionary Army",
    abilities: {
      devilFruit: "Paw-Paw",
      haki: ["Armament"],
    },
    strength: 8,
    isEmperor: false,
    isWarlord: true,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Boa Hancock",
    image: "images/hancock.jpg",
    affiliation: "Kuja Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "Love-Love",
      haki: ["Conquerors", "Armament", "Observation"],
    },
    strength: 7,
    isEmperor: false,
    isWarlord: true,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Trafalgar D. Water Law",
    image: "images/law.jpg",
    affiliation: "Heart Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "Love-Love",
      haki: ["Armament", "Observation"],
    },
    strength: 8,
    isEmperor: false,
    isWarlord: true,
    isWorstGeneration: true,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Bepo",
    image: "images/bepo.jpg",
    affiliation: "Heart Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: null,
      haki: [],
    },
    strength: 5,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Eustass Kid",
    image: "images/kid.jpg",
    affiliation: "Kid Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: "Magnet-Magnet",
      haki: ["Conquerors", "Armament", "Observation"],
    },
    strength: 8,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: true,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Killer",
    image: "images/killer.jpg",
    affiliation: "Kid Pirates",
    faction: "Pirate",
    abilities: {
      devilFruit: null,
      haki: ["Armament", "Observation"],
    },
    strength: 7,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: true,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Dog Storm",
    image: "images/inu.jpg",
    affiliation: "Mink Tribe",
    faction: "Mink",
    abilities: {
      devilFruit: null,
      haki: ["Armament", "Observation"],
    },
    strength: 7,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Cat Viper",
    image: "images/neko.jpg",
    affiliation: "Mink Tribe",
    faction: "Mink",
    abilities: {
      devilFruit: null,
      haki: ["Armament", "Observation"],
    },
    strength: 7,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
  {
    name: "Donquixote Rosinante",
    image: "images/corazon.jpg",
    affiliation: "SWORD/Donquixote Pirates",
    faction: "Navy/Pirate",
    abilities: {
      devilFruit: "Calm-Calm",
      haki: [],
    },
    strength: 6,
    isEmperor: false,
    isWarlord: false,
    isWorstGeneration: false,
    isAdmiral: false,
    isKing: false,
  },
];
